NuGetFight/Controllers/ChocolateyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NuGetFight.Data;
using NuGetFight.Data.Connectors;
using NuGetFight.Data.Models;
using NuGetFight.ViewModels;

namespace NuGetFight.Controllers
{
    public class ChocolateyController: NuGetControllerBase
    {
        private List<FightSuggestion> GetSuggestedFights()
        {
            List<FightSuggestion> suggestedList = new List<FightSuggestion>();
            suggestedList.Add(new FightSuggestion("chocolatey", "git", "hg"));
            suggestedList.Add(new FightSuggestion("chocolatey", "vim", "notepad"));
            suggestedList.Add(new FightSuggestion("chocolatey", "7zip", "winrar"));

            return suggestedList;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(new FightInputModel() { SuggestedFights = GetSuggestedFights() });
        }

        [HttpPost]
        public ActionResult Index(FightInputModel model)
        {
            return RedirectToAction("Fight", new { @query1 = model.Query1.Trim(), @query2 = model.Query2.Trim() });
        }

        [HttpGet]
        public ActionResult Fight(FightInputModel inputModel)
        {
            inputModel.SuggestedFights = GetSuggestedFights();
            return View("Fight", Fight(inputModel, NuGetConnector.ChocolateyConnectionString, FightSources.Chocolatey));
        }
    }
}

NuGetFight/Controllers/MyGetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NuGetFight.Data;
using NuGetFight.Data.Models;
using NuGetFight.ViewModels;

namespace NuGetFight.Controllers
{
    //under construction
    public class MyGetController : NuGetControllerBase
    {
        private const string MyGetUrl = "http://www.myget.org/F/{0}";
        [HttpGet]
        public ActionResult Index()
        {
            return View(new MyGetFightInputModel());
        }

        [HttpPost]
        public ActionResult Index(MyGetFightInputModel model)
        {
            return RedirectToAction("Fight", new { @query1 = model.Query1.Trim(), @query2 = model.Query2.Trim(), @mygetFeedName = model.MyGetFeedName});
        }

        [HttpGet]
        public ActionResult Fight(MyGetFightInputModel inputModel)
        {
            return View("Fight", Fight(inputModel, string.Format(MyGetUrl,inputModel.MyGetFeedName), FightSources.MyGet, inputModel.MyGetFeedName));
        }

    }
}

NuGetFight/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>

    <link href="@Url.Content("~/Content/Styles/Site.less")" rel="stylesheet" type="text/css" />
    @RenderSection("ExtraStylesheets", false)
    <link href="@Url.Content("~/Content/Styles/Site.mobile.less")" rel="stylesheet" type="text/css" media="handheld, screen and (max-width: 650px), screen and (max-device-width: 650px)" />
    
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/nugetfight.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/symbolsource.js")" type="text/javascript"></script>
    @if (System.Configuration.ConfigurationManager.AppSettings["loadGAnalytics"] != null
        && Convert.ToBoolean(System.Configuration.ConfigurationManager.AppSettings["loadGAnalytics"]))
    {
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-32309592-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
    }
</head>
<body>
    <div class="wrapper">
        <header>
            <div>
                <h1>@ViewBag.Title</h1>
                <h2>@ViewBag.CatchPhrase</h2>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("NuGet Fight", "Index", "Home")</li>
                        <li>@Html.ActionLink("Chocolatey Fight", "Index", "Chocolatey")</li>
                        <li>@Html.ActionLink("MyGet Fight", "Index", "MyGet")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                    </ul>
                </nav>
            </div>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <div id="push"></div>
    </div>
    <footer>
        <p>
            Brought to you by <a href="http://twitter.com/koenmetsu">@@koenmetsu</a> and <a href="http://twitter.com/kevinpelgrims">@@kevinpelgrims</a>
            <span id="disclaimer">@Html.ActionLink("disclaimer", "Disclaimer", "Home")</span>
        </p>
    </footer>
</body>
</html>

NuGetFight/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}